package com.shadowmesh.app

import uniffi.shadowmesh.*

enum class ConnectionInteractionMethod { TAP, SLIDE }

data class SpeedTestState(
    val isRunning: Boolean = false,
    val result: SpeedTestResult? = null,
    val error: String? = null,
    val progress: Float = 0f,
)

data class VPNUiState(
    val vpnManager: VpnManager? = null,
    val apiClient: ApiClient? = null,
    val killSwitchManager: KillSwitchManagerInterface? = null,
    val securityEventLogger: SecurityEventLogger? = null,
    val networkDetector: NetworkDetector? = null,
    val status: ConnectionStatus = ConnectionStatus.DISCONNECTED,
    val selectedNode: VpnNode? = null,
    val nodes: List<VpnNode> = emptyList(),
    val favoriteNodeIds: Set<String> = emptySet(),
    val nodeSearchQuery: String = "",
    val isLoadingNodes: Boolean = false,
    val isConnecting: Boolean = false,
    val isActivated: Boolean = false,
    val activationCode: String? = null,
    val showActivationScreen: Boolean = false,
    val isActivating: Boolean = false,
    val errorMessage: String? = null,
    val connectionMessage: String? = null,
    val userSettings: UserSettings = UserSettings(QuantumResistanceLevel.NONE, false, false, false, emptyList()),
    val connectionStats: ConnectionStats = ConnectionStats(0uL, 0uL, 0uL, 0uL, 0L, 0L),
    val killSwitchEnabled: Boolean = false,
    val killSwitchState: KillSwitchState? = null,
    val killSwitchAuditLog: List<KillSwitchEvent> = emptyList(),
    val dnsLeakProtectionEnabled: Boolean = true,
    val isKillSwitchLoading: Boolean = false,
    val killSwitchError: String? = null,
    val trafficModePreference: TrafficModePreference = TrafficModePreference.AUTO,
    val isSecurityLockEnabled: Boolean = false,
    val isPanicArmed: Boolean = false,
    val splitTunnelConfig: SplitTunnelConfig = SplitTunnelConfig(false, SplitTunnelMode.EXCLUDE, emptyList()),
    val customDNSServers: List<String> = emptyList(),
    val showCustomDNSSettings: Boolean = false,
    val showVPNGuideModal: Boolean = false,
    val interactionMethod: ConnectionInteractionMethod = ConnectionInteractionMethod.SLIDE,
    val isInitialized: Boolean = false,
    val isPanicTriggered: Boolean = false,
    val isCamouflageEnabled: Boolean = false,
    val isQuantumTunnelingActive: Boolean = false,
    val isScreenshotEnabled: Boolean = false,
    val isIntegrityCompromised: Boolean = false,
    val isSessionFrozen: Boolean = false,
    val assignedIp: String? = null,
    val advancedStealthQuantum: Boolean = false,
    val speedTestState: SpeedTestState = SpeedTestState(),
    val planName: String = "Solo",
    val devicesRemaining: Int = 0,
    val remainingDays: Long = 0,
    val quantumBytesTotal: ULong = 0uL,
    val realityBytesTotal: ULong = 0uL,
    val networkReport: NetworkReport? = null,
    val isDetectingNetwork: Boolean = false,
    val pausedUntil: Long? = null,
    val totalBytesThisMonth: ULong = 0uL,
    val securityEvents: List<SecurityEvent> = emptyList(),
    val qrToken: String? = null,
    val qrStatus: String? = null,
    val isAdmin: Boolean = false,
    val isMfaEnabled: Boolean = false,
    val isPasskeyEnabled: Boolean = false,
    val showMfaSetup: Boolean = false,
    val mfaQrCode: String? = null,
    val mfaSecret: String? = null,
    val themeColor: Long = 0xFF6366F1,
    val backgroundStyle: String = "Cyber Nebula",
    val isRooted: Boolean = false,
    val showRootWarning: Boolean = false,
    val isTunnelVerified: Boolean = false,
    val lastVerificationTime: Long = 0L,
    val isEbpfActive: Boolean = false,
    val isDiscoveryResilient: Boolean = false,
    val isCanaryToken: Boolean = false,
    val isSovereignNode: Boolean = false,
    val isGlassesConnected: Boolean = false,
    val quantumLevel: uniffi.shadowmesh.QuantumResistanceLevel = uniffi.shadowmesh.QuantumResistanceLevel.NONE,
    val featureFlags: Map<String, Boolean> = emptyMap(),
    val prepareVpnTrigger: Boolean = false,
)
